### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mduchev** [danielmahon/atom-open-last-project#14] opened 2015-01-18 22:09 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/mihail/.atom/packages/open-last-project/lib/open-last-project.js:37:9)
```

**Comment by steelbrain** [comment] 2015-01-26 06:48
Duplicate of #13

**Closed** 2015-02-03 17:57 UTC
